server {
    server_name mn_dashboard.ejar2.com;

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/mn_dashboard.ejar2.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mn_dashboard.ejar2.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    client_max_body_size 1G;

    location / {
        include proxy_params;
        proxy_pass http://localhost:8089;

        # تمرير الهيدر
        proxy_set_header v-app $http_v_app;

        # ❌ تعطيل الكاش بالكامل
        proxy_buffering off;
        proxy_cache off;
        proxy_no_cache 1;
        proxy_cache_bypass 1;

        # ❌ منع الكاش من المتصفح
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Expires 0 always;
    }
}

server {
    server_name mn_dashboard.ejar2.com;

    listen 80;
    return 301 https://$host$request_uri;
}